return {
	ensure_installed = {
		"vim",
		"lua",
		"luadoc",
		"luap",
		"python",
		"markdown",
		"markdown_inline",
		"bash",
		"regex",
		"vimdoc",
		"rust",
		"hyprlang",
		"yaml",
		"tmux",
		"make",
		"bibtex",
		"fish",
		"toml",
		"matlab",
		"css",
		"printf",
		"query",
		"json",
		"jsonc",
	},
	highlight = { enable = true, disable = { "latex" }, use_languagetree = true },
	indent = { enable = true },
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = false,
			node_decremental = "<bs>",
		},
	},
	textobjects = {
		move = {
			enable = true,
			goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer", ["]a"] = "@parameter.inner" },
			goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer", ["]A"] = "@parameter.inner" },
			goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer", ["[a"] = "@parameter.inner" },
			goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer", ["[A"] = "@parameter.inner" },
		},
	},
}
