return {
	ensure_installed = {
		"vim",
		"luap",
		"python",
		"markdown",
		"markdown_inline",
		"bash",
		"regex",
		"vimdoc",
		"rust",
		"hyprlang",
		"yaml",
		"tmux",
		"make",
		"fish",
		"toml",
		"matlab",
		"css",
		"printf",
		"query",
		"json",
		"jsonc",
		"html",
		"typst",
		"latex",
		"bibtex",
	},
	highlight = {
		enable = true,
		disable = { "latex", "bibtex" },
		use_languagetree = true,
	},
	-- indent = { enable = true },
	-- textobjects = {
	-- 	move = {
	-- 		enable = true,
	-- 		goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer", ["]a"] = "@parameter.inner" },
	-- 		goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer", ["]A"] = "@parameter.inner" },
	-- 		goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer", ["[a"] = "@parameter.inner" },
	-- 		goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer", ["[A"] = "@parameter.inner" },
	-- 	},
	-- },
}
