
-- ltex_plus = {
-- 	settings = {
-- 		ltex = {
-- 			-- statusBarItem = true,
-- 			clearDiagnosticsWhenClosingFile = false,
-- 			enabled = true,
-- 			additionalRules = {
-- 				enablePickyRules = true,
-- 				motherTongue = "en-US",
-- 			},
-- 			-- checkFrequency = "save",
-- 			language = "en-US",
-- 		},
-- 	},
-- },
