
-- 			ruff = {
-- 				cmd_env = { RUFF_TRACE = "messages" },
-- 				init_options = {
-- 					settings = {
-- 						logLevel = "error",
-- 						configurationPreference = "filesystemFirst",
-- 						codeAction = {
-- 							fixViolation = {
-- 								enable = true,
-- 							},
-- 						},
-- 						lint = {
-- 							preview = true,
-- 						},
-- 						format = {
-- 							preview = true,
-- 						},
-- 						disableRuleComment = {
-- 							enable = false,
-- 						},
-- 					},
-- 				},
-- 			},
-- 		-- 	ruff = function(client)
-- 		-- 		client.server_capabilities.hoverProvider = false
-- 		-- 	end,
-- 		-- setup = {
-- 		-- 	-- [ruff] = function()
-- 		-- 	-- 	LazyVim.lsp.on_attach(function(client, _)
-- 		-- 	-- 		-- Disable hover in favor of Pyright
-- 		-- 	-- 		client.server_capabilities.hoverProvider = false
-- 		-- 	-- 	end, ruff)
-- 		-- 	-- end,
-- 		-- },
